textautogeneratefilecache.h - include QString
fixes:
```
textautogeneratefilecache.h:16:19: error: unknown type name 'QString'
   16 |     [[nodiscard]] QString cacheFilePath(const QByteArray &attachmentId);
      |                   ^
textautogeneratefilecache.h:16:47: error: unknown type name 'QByteArray'
```

(cherry picked from commit 4b85dc9d269edab9e6ca7216cce539d6705b266e)